services:
  streamlit_app:
    build: .
    ports:
      - "8502:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      # - PORT=8501 # Cloud Run injects this automatically. Locally, you can set it here.
