mappings:
  COUNTY:
    name: "縣市"
    codes:
      1: "臺北市"
      2: "新北市"
      3: "桃園市"
      4: "臺中市"
      5: "臺南市"
      6: "高雄市"
      7: "基隆市"
      8: "新竹市"
      9: "嘉義市"
      10: "新竹縣"
      11: "苗栗縣"
      12: "彰化縣"
      13: "南投縣"
      14: "雲林縣"
      15: "嘉義縣"
      16: "屏東縣"
      17: "臺東縣"
      18: "花蓮縣"
      19: "宜蘭縣"
      20: "澎湖縣"
      21: "金門縣"
      22: "連江縣"
      98: "資料異常(等於0)"
      99: "資料缺失"

  TOT_AREA_SNAP_PING_GROUP:
    name: "坪數區間"
    codes:
      11: "15坪以下"
      12: "15-19坪"
      13: "19-25坪"
      14: "25-29坪"
      15: "29-35坪"
      16: "35-39坪"
      17: "39-45坪"
      18: "45-49坪"
      19: "49-55坪"
      20: "55-59坪"
      21: "59-65坪"
      22: "65-69坪"
      23: "70坪以上"
      98: "資料異常(等於0)"
      99: "資料缺失"

  B_AGE_FINISH_GROUP:
    name: "屋齡區間"
    codes:
      11: "1年以下"
      12: "1-5年"
      13: "5-10年"
      14: "10-15年"
      15: "15-20年"
      16: "20-25年"
      17: "25-30年"
      18: "30-40年"
      19: "40-50年"
      20: "50年以上"
      98: "資料異常(小於0)"
      99: "資料缺失"

  MATERIALS_GROUP_NEW:
    name: "構造別"
    codes:
      1: "鋼骨鋼筋混擬土造"
      2: "鋼骨鋼筋混擬土造"
      3: "鋼骨鋼筋混擬土造"
      4: "鋼筋混擬土造"
      5: "預鑄混擬土造"
      6: "加強磚造"
      7: "其他"
      8: "其他"
      9: "其他"
      98: "資料異常(等於0)"
      99: "資料缺失"

  BUILDING_FLOOR_SNAP_GROUP:
    name: "樓層區間"
    codes:
      11: "1-3層"
      12: "4-5層"
      13: "6-10層"
      14: "11-15層"
      15: "16-20層"
      16: "20層以上"
      98: "資料異常(0層以下)"
      99: "資料缺失"

  PURPOSE_GROUP:
    name: "使用類別"
    codes:
      1: "住家用"
      2: "住商用"
      3: "住工用"
      4: "國有住宅"
      5: "其他"
      99: "資料缺失"

  REGISTER_REASON_GROUP:
    name: "登記原因"
    codes:
      1: "買賣"
      2: "第一次登記"
      3: "繼承"
      4: "贈與"
      5: "拍賣"
      6: "其他"
      99: "資料缺失"

  IS_OWNED:
    name: "是否有所有權人"
    codes:
      0: "否"
      1: "是"
      99: "資料缺失"

columns_order:
  - DATA_YR
  - IS_OWNED
  - COUNTY
  - TOT_AREA_SNAP_PING_GROUP
  - B_AGE_FINISH_GROUP
  - MATERIALS_GROUP_NEW
  - BUILDING_FLOOR_SNAP_GROUP
  - PURPOSE_GROUP
  - REGISTER_REASON_GROUP
  - CNT
