mappings:
  COUNTY_N:
    name: "縣市"
    dtype: "category"
    codes:
      1: "臺北市"
      2: "新北市"
      3: "桃園市"
      4: "臺中市"
      5: "臺南市"
      6: "高雄市"
      7: "基隆市"
      8: "新竹市"
      9: "嘉義市"
      10: "新竹縣"
      11: "苗栗縣"
      12: "彰化縣"
      13: "南投縣"
      14: "雲林縣"
      15: "嘉義縣"
      16: "屏東縣"
      17: "臺東縣"
      18: "花蓮縣"
      19: "宜蘭縣"
      20: "澎湖縣"
      21: "金門縣"
      22: "連江縣"
      98: "資料異常(等於0)"
      99: "資料缺失"

  AREA_ALL_SUM_PING_GROUP:
    name: "坪數區間"
    dtype: "Int64"
    codes:
      11: "15坪以下"
      12: "15-19坪"
      13: "19-25坪"
      14: "25-29坪"
      15: "29-35坪"
      16: "35-39坪"
      17: "39-45坪"
      18: "45-49坪"
      19: "49-55坪"
      20: "55-59坪"
      21: "59-65坪"
      22: "65-69坪"
      23: "70坪以上"
      98: "資料異常(等於0)"
      99: "資料缺失"

  HOU_DEPR_YEAR_OLD_GROUP:
    name: "屋齡區間"
    dtype: "Int64"
    codes:
      11: "1年以下"
      12: "1-5年"
      13: "5-10年"
      14: "10-15年"
      15: "15-20年"
      16: "20-25年"
      17: "25-30年"
      18: "30-40年"
      19: "40-50年"
      20: "50年以上"
      98: "資料異常(小於0)"
      99: "資料缺失"

  STRUC_MAX_GROUP:
    name: "構造別"
    dtype: "Int64"
    codes:
      1: "鋼骨鋼筋混凝土造"
      2: "鋼骨鋼筋混凝土造"
      3: "鋼骨鋼筋混凝土造"
      4: "鋼筋混凝土造"
      5: "壁式預鑄鋼筋混凝土造"
      6: "加強磚造"
      7: "其他"
      8: "其他"
      9: "其他"
      98: "資料異常(等於0)"
      99: "資料缺失"

  HOU_FLOOR_MAX_GROUP:
    name: "樓層區間"
    dtype: "Int64"
    codes:
      11: "1-3層"
      12: "4-5層"
      13: "6-10層"
      14: "11-15層"
      15: "16-20層"
      16: "20層以上"
      98: "資料異常(0層以下)"
      99: "資料缺失"

columns_order:
  - DATA_YR
  - COUNTY_N
  - AREA_ALL_SUM_PING_GROUP
  - HOU_DEPR_YEAR_OLD_GROUP
  - STRUC_MAX_GROUP
  - HOU_FLOOR_MAX_GROUP
  - CNT
